services:
  adsconfiguration.api:
    image: adsconfiguration.api
    container_name: adsconfiguration.api
    build:
      context: .
      dockerfile: AdsConfiguration.API/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
    ports:
        - "5000:80"
    networks:
        - adsconfiguration
    volumes:
      - adsconfiguration:/app/AdsConfiguration.API/Uploads

  adsconfiguration.ui:
    image: adsconfiguration.ui
    container_name: adsconfiguration.ui
    build:
      context: .
      dockerfile: AdsConfiguration.UI/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
    ports:
        - "8080:80"
    networks:
        - adsconfiguration

networks:
  adsconfiguration:
    driver: bridge

volumes:
    adsconfiguration: